### ISSUE TITLE
Error: object 'genome_version' not found

### ISSUE THREAD

**Issue by JAYRJPT** [honzee/RNAseqCNV#10]
Hello Jan,

First of all thanks for upgrading the package with GRCh38. 
I have uninstalled the old package and reinstalled the updated one. However when I am running the package I am getting an issue.
Here is my command-
```
> RNAseqCNV_wrapper(config = "/media/deepak/jay_doc/config.txt", metadata = "/media/deepak/jay_doc/META.csv", snv_format = "vcf", genome_version == "GRCh38")
[1] "Analysis initiated"
[1] "Normalization for sample: B31 completed"
[1] "Preparing file with snv information for: B31"
Reading in vcf file..
Extracting depth..
Extracting reference allele and alternative allele depths..
Needed information from vcf extracted
Finished reading vcf
[1] "Estimating chromosome arm CNV: B31"
Error: object 'genome_version' not found
```
Is there any mistake in the parameter? or should I use the shinny app?

Thanks,

Jay

**Comment by honzee** [comment]
Hi Jay,

you should try: "=" instead of "==" when inputting the parameter:

RNAseqCNV_wrapper(config = "/media/deepak/jay_doc/config.txt", metadata = "/media/deepak/jay_doc/META.csv", snv_format = "vcf", genome_version = "GRCh38")

Let me know if this solves your problems,
Best,
Jan
