### ISSUE TITLE
Warning messages: 1: In colnames(count_norm)[2:length(count_norm)] <- paste0("control_", : number of items to replace is not a multiple of replacement length 2: Removed 2 rows containing missing values (geom_label).

### ISSUE THREAD

**Issue by honzee** [honzee/RNAseqCNV#2]
Dear Jan
After updating my vcf file, I am able to get the output result.
However I got some warning meassge-
Warning messages:
1: In colnames(count_norm)[2:length(count_norm)] <- paste0("control_", :
number of items to replace is not a multiple of replacement length
2: Removed 2 rows containing missing values (geom_label).

Please let me know whether to be worried about this warning message or not.
Thanks for your cooperation.
Regards
Jay

**Comment by honzee** [comment]
The first warning should not affect the output of RNAseqCNV. That said, thank you for pointing it out, it will be addressed in the next update.

The second warning indicates that some labels have not been generated. However, both the upper panel (expression) and the lower panel (MAF density graphs) of the main figure have labels associated with them. Could you please check the output figure, which panel is affected by the missing labels?

Best,
Jan

**Comment by JAYRJPT** [comment]
The output main figure is however little bit different from the sample figure given in the package.
1. The y axis of expression panel showing **log2 fold change of expression** rather than **normalized expression**( as shown in https://github.com/honzee/RNAseqCNV).
2. The value inside the **Low** and **High** Box ( uppermost portion of the expression panel) is showing 0.
3. The value of the peak dist. in the MAF panel is showing the value 0.

Is there a way to upload the figure here?

Thanks and Regards.

**Comment by honzee** [comment]
Yes, you can attach files by dragging & dropping or pasting them in the text box on the Github page. However, if that does not work for you, you can send it to me by email:
honzabarinka@seznam.cz

1. The y-axis description was changed in order to be more exact. While the top panel is constructed from normalized expression data, subsequently log2 fold change values from the baseline are then visualized.

2. The value inside the box has the estimated copy number change inside it: 0 for no gain/deletion), 1 for 1-copy gain, -1 for 1-copy deletion and 2 for 2-copy gain. The color of the box signifies whether the estimation was low/high quality, which is determined by the proportion of trees in a random forest estimator, which agreed on this copy number change. In summary, if you have only zeros in the boxes, RNAseqCNV estimated that there are no copy number changes.

3. The peak distance is calculated only when 2 significant peaks are detected by RNAseqCNV. In case there are no copy number changes, the expected peak distances would be zero.

If you have any other questions, I will be glad to help,
Jan

**Comment by JAYRJPT** [comment]
Thanks for the explanation.
My issues are resolved.
I will let you know if I have any issues in future.
Thanks and Regards,
Jay
