### ISSUE TITLE
Format for gene level counts

### ISSUE THREAD

**Issue by anashank** [honzee/RNAseqCNV#20]
Hi, I was wondering if it would be possible to use the output from tools like Salmon, which has a different method of counting reads compared to tools like HTSeq?

**Comment by honzee** [comment]
Hi,

thanks for the question! We have yet to test running RNAseqCNV with output count files from salmon. However, I think as input, it should work very similarly to HTSeq. Just make sure, that the count files are in the format specified in README.

Best,
Jan

**Comment by anashank** [comment]
Thank you!
