### ISSUE TITLE
What GATK parameters to use to generate VCF?

### ISSUE THREAD

**Issue by NadineWolgast** [honzee/RNAseqCNV#24]
Hey, 

Thank you for your great tool!
I'm trying to decide which tool/ workflow to use in order to generate the input vcf file. I've tried so far CTAT mutations and implemented a workflow using GATK. I have tried both output vcf files as input and compared the resulting RNAseqCNV output. They are different for the same sample.  
I was wondering which GATK workflow you are using with which parameters and filters to generate your files. Thank you in advance! Nadine

**Comment by honzee** [comment]
Hi Nadine,

thank you for your interest in our tool. We always use the latest version of the GATK pipeline with default parameters.

The goal should be to get a reliable set of germline variant mutations. Also for this reason in RNAseqCNV, we use dbSNP database to keep only the known variants and we filter out the very low and very high MAF variants. 

Anyway, I would be interested in how different are the results from the CTAT and GATK pipelines.

Best,
Jan

**Comment by NadineWolgast** [comment]
Hey Jan, 
Thank you for your answer! I can send you the plots/tables via email if you are interested.

Cheers, Nadine
