### ISSUE TITLE
link RNAseq count to CNV

### ISSUE THREAD

**Issue by hellocita** [honzee/RNAseqCNV#3]
There is an RNA seq data from illuminar, single-end, 2 lanes and 10-12 samples per lane. including 3 disease and control samples respectively. Can I find the association of the expression difference of this data, with a public array data investigating the de novo mutation in the disease, which has more samples?
Thanks!

**Comment by honzee** [comment]
Hi, thank you for the question. RNAseqCNV repository provides an R package for inferring large scale CNV from users RNA-seq data. Unfortunately, RNAseqCNV's purpose is not to compare expression between user samples and public array data, neither to look for de novo mutations. In case I have misunderstood your question, please try to rephrase it so we are on the same page.
Best,
Jan
