### ISSUE TITLE
Warning: Error in : Problem with `filter()` input `..1`.

### ISSUE THREAD

**Issue by deppworld** [honzee/RNAseqCNV#5]
Hi Honzee
I was trying to analyse my sample with your RNAseqCNV but facing error during data analysis. Please look into this and suggest some solutions.

ERROR IN Rstudio:

> library(RNAseqCNV)
> launchApp()
Loading required package: shiny

Listening on http://127.0.0.1:3981
Warning in readLines(input$config$datapath) :
  incomplete final line found on 'C:\Users\ngs\AppData\Local\Temp\RtmpKkkqvG/86a5f01f4519aa95e37e6d11/0'
[1] "Normalization for sample: Sample_3 completed"
[1] "Preparing file with snv information for: Sample_3"
Reading in vcf file..
Extracting depth..
Extracting reference allele and alternative allele depths..
Needed information from vcf extracted
Finished reading vcf
Warning in setDT(list(l = lower, u = upper)) :
  Some columns are a multi-column type (such as a matrix column): [1, 2]. setDT will retain these columns as-is but subsequent operations like grouping and joining may fail. Please consider as.data.table() instead which will create a new column for each embedded column.
Warning: Error in : Problem with `filter()` input `..1`.
x i.l is type list which is not supported by data.table join
i Input `..1` is `|...`.
  175: <Anonymous>
Warning: Error in : Problem with `filter()` input `..1`.
x i.l is type list which is not supported by data.table join
i Input `..1` is `|...`.
  175: <Anonymous>

ERROR in APP window: 

[31mx[39m i.l is type list which is not supported by data.table join
[34mi[39m Input `..1` is `|...`.

System details:
> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          0.2                         
year           2020                        
month          06                          
day            22                          
svn rev        78730                       
language       R                           
version.string R version 4.0.2 (2020-06-22)
nickname       Taking Off Again

Kindly do needful to resolve this issue.

Thanks and regards

Deepak

**Comment by honzee** [comment]
Dear Deepak,

thank you for trying out RNAseqCNV, I hope we can solve the issue soon.
A similar issue was already raised by a different user, I suspect it might be due to a recent update in code. I will resolve it and will let you know after.
If this would not solve your problems, I will look more closely into your case individually.

Best,
Jan

**Comment by deppworld** [comment]
Dear JanThanks, waiting for update. RegardsDeepakSent from my Samsung Galaxy smartphone.
-------- Original message --------From: honzee <notifications@github.com> Date: 11/08/2020  20:52  (GMT+05:30) To: honzee/RNAseqCNV <RNAseqCNV@noreply.github.com> Cc: Deepak Verma <depp@live.in>, Author <author@noreply.github.com> Subject: Re: [honzee/RNAseqCNV] Warning: Error in : Problem with `filter()` input `..1`. (#5) 
Dear Deepak,
thank you for trying out RNAseqCNV, I hope we can solve the issue soon.
A similar issue was already raised by a different user, I suspect it might be due to a recent update in code. I will resolve it and will let you know after.
If this would not solve your problems, I will look more closely into your case individually.
Best,
Jan

**Comment by honzee** [comment]
Dear Deepak,

I have updated the package, you can try to reinstall RNAseqCNV, but I am not sure if it will solve your issues.

I think the issue is either in 1. incompatible input or 2. package versioning

1. To check for the correct input format or for me to make the package work for your specific data, I would need to see your data first. It would be great if you could send me the first few lines of your vcf file without the header.

2. To see what versions of packages you are working with, please use:
utils::sessionInfo()
and send me the result. Some of the package versions you are using might be incompatible with RNAseqCNV at the moment. 

Thank you,
Jan

**Comment by deppworld** [comment]
Dear JanThank you so much for your quick response.  I will share you the results as soon as I run it.Best regardsDeepakSent from my Samsung Galaxy smartphone.
-------- Original message --------From: honzee <notifications@github.com> Date: 12/08/2020  22:50  (GMT+05:30) To: honzee/RNAseqCNV <RNAseqCNV@noreply.github.com> Cc: Deepak Verma <depp@live.in>, Author <author@noreply.github.com> Subject: Re: [honzee/RNAseqCNV] Warning: Error in : Problem with `filter()` input `..1`. (#5) 
Dear Deepak,
I have updated the package, you can try to reinstall RNAseqCNV, but I am not sure if it will solve your issues.
I think the issue is either in 1. incompatible input or 2. package versioning


To check for the correct input format or for me to make the package work for your specific data, I would need to see your data first. It would be great if you could send me the first few lines of your vcf file without the header.


To see what versions of packages you are working with, please use:
utils::sessionInfo()
and send me the result. Some of the package versions you are using might be incompatible with RNAseqCNV at the moment.


Thank you,
Jan

**Comment by honzee** [comment]
Dear Deepak,

I managed to replicate the error by updating dplyr and tidyselect, corrected it subsequently, and uploaded the new RNAseqCNV version to GitHub. I hope this works. Please let me know.

Best,
Jan
