### ISSUE TITLE
Figure interpretation

### ISSUE THREAD

**Issue by honzee** [honzee/RNAseqCNV#8]
I have attached the main figure generated from the package. I dont know why some of the chromososmes showing low quality and 3 of them showing "ab" instead of some numeric value.
It will be appreciated if you can look into the figure and kindly share your opinion. 

![B1_CNV_main_fig](https://user-images.githubusercontent.com/61318909/112936769-0e616680-9144-11eb-885b-38fef9dfb3f3.png)

_Originally posted by @JAYRJPT in https://github.com/honzee/RNAseqCNV/issues/7#issuecomment-809918319_

**Comment by honzee** [comment]
Dear Jay,

- the red description - "low-confidence prediction" signifies that the random forest model was not overwhelmingly sure of the prediction. Because of that, I would be very careful with those predictions. 

- the "ab" means that the chromosome arms of that chromosome were predicted not to have the same copy number. To explore the arm-level predictions, you should look at the arm-level figures or CNV matrix and estimation table (more info about these outputs is in the README).

As for the interpretation of this specific graph: the expression level does not show any clear gains/deletions. The MAF graphs are showing a high peak around 0.5 mark on the x axis (except for chromosome X but that's to be expected), which means that the allele ratio is probably 1:1 in the cancer cell (there are two gene copies) or that there is a high percentage of non-cancer cells.

The optimal approach would be to test RNAseqCNV on samples, where another method of CNV detection was used (SNP array, WGS, WES) or even cytogenetics. In this way, we could find out, whether RNAseqCNV is working for your data by cross-referencing it first.

Also, may I ask what kind of RNA-seq data are you providing as input?

Best,
Jan

**Comment by JAYRJPT** [comment]
Hello Jan,
Thanks for the figure interpretation. 
Sorry I couldn't understand by  " kind of RNA-seq data".  Can you elaborate it further?

Regards,
Jay

**Comment by honzee** [comment]
Of course, my question was too vague, sorry. I wanted to ask, what type of malignancy are you studying, was the sample filtered for cancer-cells, which library preparation was used, on which machine was it sequenced?

The most important factor is probably the studied malignancy and purity of the sample, although the other factors can affect the quality of the result too.

RNAseqCNV was built primarily with childhood acute lymphoblastic leukemia in mind since the CNVs are important for determining prognosis and it is easier to acquire samples with high cancer-cell purity. 

Best,
Jan

**Comment by JAYRJPT** [comment]
We are studying B-ALL. All Patients samples were having 80-90% leukemic blast. Samples were sequenced in Illumina Hiseq. Paired end library (150x2) is prepared for all the samples.

**Comment by honzee** [comment]
That should be fitting data for the package. I would love to hear more feedback from you regarding the results. If there are other figures or anything you would like to discuss, I would be glad.

Best,
Jan

**Comment by JAYRJPT** [comment]
Dear Jan,
I have attached the figure of one of the hyperdiploid B-ALL case
Can you give some comments on this as I am unable to draw any CNA information from it.

![SAMPLE_11_CNV_main_fig](https://user-images.githubusercontent.com/61318909/119805832-3b8d8380-beff-11eb-80bc-8b26b5b67be7.png)


Thanks,
Jay

**Comment by honzee** [comment]
Dear Jay,

it is true, that the figure seems a bit unclear (probably due to the unordinary MAF density graphs), however, I think there is some information to be drawn from it.

It looks like a high hyperdiploid sample. The higher log2 fold change level and MAF density graph with peaks around 0.33 and 0.66 suggests a 1-copy gain on chromosomes: 2, 5, 6, 8, 10, 11, 16, 17, 18. The pattern for chromosomes 14 and 21 is consistent with 2-copy gain. There is also a gain on chromosome X, but the exact number of copies is challenging to determine for this chromosome in general. Chromosomes 1, 3, 4, 7, 15, 19, 20, 22 have probably two-copies (no large, discernable CNV). The rest of the chromosomes is quite challenging to predict according to the figure - my wild guess would be: 9 partial gain, 12 subclonal gain, 13 subclonal gain.

If you would like me to elaborate more on the specifics of the interpretation, I will be glad to answer your questions.

Best,
Jan

**Comment by JAYRJPT** [comment]
Dear Jan,

Thanks for the interpretation of the figure but somehow it is still unclear to me how to interpret the result. I have read the manual and I would like to summarize what I have understood.
1. Chromosomes in which log2fold change are centered around zero and also the MAF graph is showing peak distance at zero are diploid.
2. Chromosome in which log2fold change are not centered around zero or the MAF Graph which are showing peak distance other than zero are those which showing CNA.

Please correct me if I am wrong.

Now, I would like to discuss my queries.
1. In the lower panel of the main figure, which peak distance( p arm or q ram) is shown in the MAF graph?
2. How are we differentiating MAF graph of diploid from the 2-copy gain? If the log2fold change is higher and MAF graph showing peak height other than zero, then is it 2-copy gain?
3. How to interpret the MAF graph of single copy gain chromosome and LOH?
4. If there only gain in one arm of the chromosome then will it be considered as single gain?

Thanks, 

Jay

**Comment by honzee** [comment]
Dear Jay,

thank you for the questions. I will try to answer them as clearly as I can.

_Chromosomes in which log2fold change are centered around zero and also the MAF graph is showing peak distance at zero are diploid._
Yes. For the MAF density graph in diploid chromosomes, we expect one high peak around 0.5. Peak distance for such MAF graphs is not calculated and assigned a 0 value. I noticed you have some additional peaks on the sides in your figures, which are, in my opinion only a noise. We have come across a similar problem already and we have improved the result by inputing different x axis range for MAF density graph. You can do this by adding parameter to the RNAseqCNV wrapper function. I would suggest starting with this: _mafRange = c (0.1, 0.8)_ 

_Chromosome in which log2fold change are not centered around zero or the MAF Graph which are showing peak distance other than zero are those which showing CNA._
Yes, thats how it should be optimally. However, peak distance can change without CNV change (LOH) and CNV can be present when peak distance is 0 (2-copy gain). Also, the changes might be only subclonal or partial, which typically show a different and hard to identify MAF density graph shape (perhaps chromosome 12 and 13 in your figure).

_In the lower panel of the main figure, which peak distance( p arm or q ram) is shown in the MAF graph?_
Both. All of the MAFs from each single chromosome after the filtering are used to construct the density curve. You can check the arm specific density curves in the arm specific figures if you have generated them.

_How are we differentiating MAF graph of diploid from the 2-copy gain? If the log2fold change is higher and MAF graph showing peak height other than zero, then is it 2-copy gain?_
What happens most often in hyperdiploid ALL samples for 2-copy gains is, that each chromosome from the pair is duplicated once. Thus, for each allele, we end up with 2:2 ratio, which is identical MAF as the 1:1 allele ration for diploid chromosomes. In conclusion, we cannot distinguish the between the MAF density graph of such 2-copy gain and diploid chromosome. However, for 2-copy gain, the log2 fold change is usually very high (chromosome 14 and 21 in your case). That sain sometimes, there are 2-copy gains, where one single chromosome is duplicated twice. In such cases the allele ratio is 3:1, so the peak distance should be around 0.5.

_How to interpret the MAF graph of single copy gain chromosome and LOH?_
The allele ratio for single copy gain is 2:1, thus we expect the two peaks to be around 0.33 and 0.66 and the peak distance to be around 0.33. In copy neutral LOH, the allele ratio is 1:0, therefore we would expect the peaks to be around 1 and 0. Due to the nature of RNAseq data, there are also alleles with MAF other than 0 and 1, but in general, the peaks should be wide apart from each other (like for the chromosome X in your figure).

_If there only gain in one arm of the chromosome then will it be considered as single gain?_
If the random forest prediction model assigns one arm as 1-copy gain and the other as diploid, the final verdict will be **ab**. For the figure, I would expect, that the MAF graph would have small peaks around 0.5, 0.33 and 0.66. The  log2 fold change boxplot would be slighlty higher, but not to the level of normal 1-copy gain. However, you can generate arm specific figures with RNAseqCNV, where these changes should be more clear.

Hope I answered your questions clearly, but be free to keep the questions coming.

Best,
Jan
