### ISSUE TITLE
Error in DESeqDataSet: counts matrix should be numeric, currently it has mode: logical

### ISSUE THREAD

**Issue by deb0612** [honzee/RNAseqCNV#9]
Dear sir,
When I tried to use shiny app to analyze samples,
it shows: 
Warning: Error in DESeqDataSet: counts matrix should be numeric, currently it has mode: logical
  [No stack trace available]

**Comment by honzee** [comment]
Dear deb0612,

thank you for trying out our package. I will look into the issue in the upcoming days and I will keep you updated.

Best,
Jan

**Comment by honzee** [comment]
Dear deb0612,

the shiny application was lacking behind the rest of the package since the hg38 genome version was missing there. This was possibly causing your issues. In the latest commit, this has been changed. Therefore, I suggest trying to download the newer version of RNAseqCNV.

If your issues still persist, please do not hesitate to contatct me, since I always appreciate an opportunity to make the package better.

Best,
Jan

**Comment by deb0612** [comment]
Dear sir,
I re-install the RNAseqCNV, and encountered the same error.
Would you tell me how to download the latest version?

**Comment by honzee** [comment]
The shiny

**Comment by honzee** [comment]
Have you tried using the wrapper function?

**Comment by deb0612** [comment]
I don't really understand this function
Could you show me how to use it?

**Comment by honzee** [comment]
Some examples are included in the README for this package. I copied some of it below:

# Example
library(RNAseqCNV)

# example of wrapper function 
RNAseqCNV_wrapper(config = "path/to/config", metadata = "path/to/metadata", snv_format = "vcf", genome_version = "GRCh38")

For this to work, the input (config file, metadata table, count files and vcf files) need to be in a correct format. Please see the README for more information on the correct formating. 

If this does not help, we will investigate further.

Best,
Jan

**Comment by deb0612** [comment]
Yes, I tried.
It showed the same error:
![image](https://user-images.githubusercontent.com/29038270/122989093-0167b280-d3d5-11eb-892b-aa04e5bb063e.png)

**Comment by honzee** [comment]
This function is generally used by the users without problems when the input is formatted accordingly to the package. So I suspect there might be an issue in the config file, the metadata file, or the count files.

If you would be willing to, you could try to send me the config file, the metadata file, and the first few lines of one of the count files. Maybe I could spot the issue that way.

Hope we get the package working for you,
Jan

**Comment by yueding1590049** [comment]
I do have the same problem,
Error in DESeqDataSet(se, design = design, ignoreRank) : 
  counts matrix should be numeric, currently it has mode: character

**Comment by honzee** [comment]
Hi,

thanks for contacting me. I think this is most likely caused by the count file formatting. You could send me the first few lines of your count files, so I could help you more easily.

Best,
Jan
